### ISSUE TITLE
CDN should use redirects for specific cases

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/JNPM#3]
Cases are:
- [ ] Particular version was not specified - redirect to URL with latest version
- [ ] Version was specified as range - redirect to URL with latest version from the range
- [ ] Path was not specified - redirect to URL with specified path from corresponding params from package.json

Example for def paths:
```
  "unpkg": "dist/vue.js",
  "jsdelivr": "dist/vue.js",
```

**Comment by PhantomYdn** [comment]
If 3rd is requested - currently it will lead to the following exception:

```java
java.lang.IllegalArgumentException: Path '/vue2-leaflet' should corresponds pattern '/([^/@]*)@?([^/]*)/(.*)'
        at org.orienteer.jnpm.cdn.CDNRequest.valueOf(CDNRequest.java:80)
        at org.orienteer.jnpm.cdn.CDNWicketResource.newResourceResponse(CDNWicketResource.java:49)
        at org.apache.wicket.request.resource.AbstractResource.respond(AbstractResource.java:630)
        at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
        at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:100)
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:899)
        at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65)
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:282)
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253)
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:275)
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:206)
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:305)
```
